class_name GameSelector
extends Widget
## Port of GameSelector (main menu) + GameSelectorOverlay.
## Community edition: the reanim-driven selector scene is replaced by the spritesheet scene in
## MainMenuLayout (assets/crop, generated by tools/menu_layout). Menu logic is unchanged.

enum { SELECTOR_OPEN, SELECTOR_NEW_USER, SELECTOR_SHOW_SIGN, SELECTOR_SUB_MENU, SELECTOR_IDLE }

const GAMESELECTOR_ADVENTURE := 100
const GAMESELECTOR_MINIGAME := 101
const GAMESELECTOR_PUZZLE := 102
const GAMESELECTOR_OPTIONS := 103
const GAMESELECTOR_HELP := 104
const GAMESELECTOR_QUIT := 105
const GAMESELECTOR_CHANGE_USER := 106
const GAMESELECTOR_STORE := 107
const GAMESELECTOR_ALMANAC := 108
const GAMESELECTOR_ZEN_GARDEN := 109
const GAMESELECTOR_SURVIVAL := 110
const GAMESELECTOR_ACHIEVEMENT := 111
const GAMESELECTOR_QUICK_PLAY := 112
const GAMESELECTOR_CREDITS := 113
const GAMESELECTOR_TREE_OF_WISDOM := 114
const GAMESELECTOR_SOCIAL := 115
const GAMESELECTOR_EDITOR := 116

const HAS_QUICKPLAY := true
const HAS_ACHIEVEMENTS := true

const CROP_DIR := "res://assets/crop/"
const INTRO_FRAMES := 60
const FLOWER_POP_FRAMES := 30
## Layout buttons that are hidden (not just inactive) while their feature is locked.
const HIDDEN_WHEN_LOCKED := ["store", "almanac", "zen_garden", "quick_play"]
## Text areas inside sprites, in sprite pixels: centre, rotation (degrees), text scale, max width.
const NAME_BAR := [Vector2(245, 598), -10.0, 1.6, 190.0]
const NAME_BAR_SHAPE := [Vector2(140, 598), Vector2(352, 560), Vector2(358, 594), Vector2(146, 632)]
const LEVEL_PLAQUE := [Vector2(162, 27), 0.0, 1.0, 60.0]
const BAR_LABEL := [Vector2(157, 40), 0.0, 1.9, 215.0]
const TROPHY_POS := Vector2(1765, 985)
const TROPHY_SCALE := 0.75
const CLOUD_SPEED := 0.12

class GameSelectorOverlay:
	extends Widget
	var owner_selector: GameSelector

	func _init(gs: GameSelector) -> void:
		owner_selector = gs
		mouse_visible = false

	func draw(g: Graphics) -> void:
		owner_selector.draw_overlay(g)

var adventure_button: NewLawnButton
var minigame_button: NewLawnButton
var puzzle_button: NewLawnButton
var options_button: NewLawnButton
var quit_button: NewLawnButton
var help_button: NewLawnButton
var store_button: NewLawnButton
var almanac_button: NewLawnButton
var zen_garden_button: NewLawnButton
var achievement_button: NewLawnButton
var quick_play_button: NewLawnButton
var credits_button: NewLawnButton
var survival_button: NewLawnButton
var change_user_button: NewLawnButton
var tree_button: NewLawnButton
var social_button: NewLawnButton
var editor_button: NewLawnButton
var overlay_widget: GameSelectorOverlay
var starting_game := false
var starting_game_counter := 0
var minigames_locked := false
var puzzle_locked := false
var survival_locked := false
var show_start_button := false
var trophy_particle: TodParticleSystem = null
var hand_reanim: Reanimation = null
var selector_state := SELECTOR_OPEN
var level := 1
var loading := false
var tool_tip: ToolTipWidget
var has_trophy := false
var unlock_selector_cheat := false
var debug_text := false
var movement_timer := 0
var current_y := 0
var destination_y := 0
var current_x := 0
var destination_x := 0
var enable_buttons_transition := false

## MainMenuLayout.ENTRIES plus runtime state: "image", "over_image", "tris", "outline_pts",
## "button_widget", "cloud_x", "pop".
var scene: Array = []
var intro_counter := 0
var _image_cache: Dictionary = {}

static func _img(id: String) -> PvzImage:
	return Res.get_image(id)

func _layout_image(name: String) -> PvzImage:
	if _image_cache.has(name):
		return _image_cache[name]
	var img: PvzImage = null
	if name.contains("/"):
		img = Res.load_image_path(name)
	elif ResourceLoader.exists(CROP_DIR + name + ".png"):
		img = PvzImage.new(load(CROP_DIR + name + ".png"))
	if img == null:
		push_warning("Missing main menu image: " + name)
	_image_cache[name] = img
	return img

func _all_buttons() -> Array:
	return [adventure_button, minigame_button, puzzle_button, options_button, quit_button, help_button, change_user_button,
		credits_button, store_button, almanac_button, survival_button, zen_garden_button, achievement_button, quick_play_button,
		tree_button, social_button, editor_button]

func _make_button(bid: int, img: PvzImage) -> NewLawnButton:
	var b := LawnButtons.make_new_button(bid, self, "", null, img, img, img)
	b.btn_no_draw = true
	b.clip = false
	b.mouse_visible = false
	b.use_polygon_shape = true
	return b

func _init() -> void:
	level = 1
	tool_tip = ToolTipWidget.new()
	current_y = y
	destination_y = current_y
	current_x = x
	destination_x = current_x

	var blank := _img("IMAGE_BLANK")
	var by_name := {}
	for key in ["adventure", "minigame", "puzzle", "survival", "options", "help", "quit", "store", "almanac", "zen_garden",
			"achievements", "quick_play", "credits", "tree", "social", "editor"]:
		by_name[key] = null
	for src in MainMenuLayout.ENTRIES:
		var e: Dictionary = src.duplicate()
		e["image"] = _layout_image(e.img)
		if e.has("poly"):
			_build_poly(e)
		if e.has("cloud"):
			e["cloud_x"] = 0.0
		if e.has("flower"):
			e["pop"] = 0
		if e.has("button"):
			e["over_image"] = _layout_image(e.img + "_highlight")
			var b := _make_button(_button_id(e.button), e.image)
			_place_button(b, e, _sprite_corners(e))
			e["button_widget"] = b
			by_name[e.button] = b
		if e.has("name_bar"):
			change_user_button = _make_button(GAMESELECTOR_CHANGE_USER, blank)
			_place_button(change_user_button, e, NAME_BAR_SHAPE)
		scene.append(e)

	adventure_button = by_name.adventure
	minigame_button = by_name.minigame
	puzzle_button = by_name.puzzle
	survival_button = by_name.survival
	options_button = by_name.options
	help_button = by_name.help
	quit_button = by_name.quit
	store_button = by_name.store
	almanac_button = by_name.almanac
	zen_garden_button = by_name.zen_garden
	achievement_button = by_name.achievements
	quick_play_button = by_name.quick_play
	credits_button = by_name.credits
	tree_button = by_name.tree
	social_button = by_name.social
	editor_button = by_name.editor

	overlay_widget = GameSelectorOverlay.new(self)
	overlay_widget.resize(0, 0, PvZ.BOARD_WIDTH, PvZ.BOARD_HEIGHT)

	App.music.make_sure_music_is_playing(PvZ.MUSIC_TUNE_TITLE_CRAZY_DAVE_MAIN_THEME)
	selector_state = SELECTOR_OPEN
	intro_counter = 0
	sync_profile(false)
	App.play_sample("SOUND_ROLL_IN")

static func _button_id(key: String) -> int:
	match key:
		"adventure": return GAMESELECTOR_ADVENTURE
		"minigame": return GAMESELECTOR_MINIGAME
		"puzzle": return GAMESELECTOR_PUZZLE
		"survival": return GAMESELECTOR_SURVIVAL
		"options": return GAMESELECTOR_OPTIONS
		"help": return GAMESELECTOR_HELP
		"quit": return GAMESELECTOR_QUIT
		"store": return GAMESELECTOR_STORE
		"almanac": return GAMESELECTOR_ALMANAC
		"zen_garden": return GAMESELECTOR_ZEN_GARDEN
		"achievements": return GAMESELECTOR_ACHIEVEMENT
		"quick_play": return GAMESELECTOR_QUICK_PLAY
		"credits": return GAMESELECTOR_CREDITS
		"tree": return GAMESELECTOR_TREE_OF_WISDOM
		"social": return GAMESELECTOR_SOCIAL
		"editor": return GAMESELECTOR_EDITOR
	return 0

# ---------------------------------------------------------------- layout geometry
## Sprite pixel space -> screen (relative to this widget), for a layout entry at design offset [param offset].
func _entry_xform(e: Dictionary, offset := Vector2.ZERO, pop := 1.0) -> Transform2D:
	var s: Vector2 = e.get("scale", Vector2.ONE) * MainMenuLayout.DESIGN_SCALE * pop
	if e.get("mirror", false):
		s.x = -s.x
	var pos: Vector2 = (e.pos + offset) * MainMenuLayout.DESIGN_SCALE
	return Transform2D(deg_to_rad(e.get("rot", 0.0)), s, 0.0, pos)

func _entry_src(e: Dictionary) -> Rect2:
	var img: PvzImage = e.image
	return e.get("src", Rect2(0, 0, img.width, img.height))

## Maps a point given in sprite pixels (top-left origin of the src rect) to screen space.
func _sprite_point(e: Dictionary, xf: Transform2D, p: Vector2) -> Vector2:
	return xf * (p - _entry_src(e).size * 0.5)

func _sprite_corners(e: Dictionary) -> Array:
	var sz := _entry_src(e).size
	return [Vector2.ZERO, Vector2(sz.x, 0), sz, Vector2(0, sz.y)]

## Sizes a button to the screen-space bounds of [param shape] (sprite pixels, clockwise) and uses it as the hit polygon.
func _place_button(b: NewLawnButton, e: Dictionary, shape: Array) -> void:
	var xf := _entry_xform(e)
	var pts: Array = []
	var bounds := Rect2()
	for i in shape.size():
		var p := _sprite_point(e, xf, shape[i])
		pts.append(p)
		bounds = Rect2(p, Vector2.ZERO) if i == 0 else bounds.expand(p)
	var bx := floori(bounds.position.x)
	var by := floori(bounds.position.y)
	b.resize(bx, by, ceili(bounds.end.x) - bx, ceili(bounds.end.y) - by)
	b.polygon_shape = pts.map(func(p: Vector2) -> Vector2: return p - Vector2(bx, by))

func _build_poly(e: Dictionary) -> void:
	var img: PvzImage = e.image
	var pts := PackedVector2Array(e.poly)
	var bounds := Rect2(pts[0], Vector2.ZERO)
	for p in pts:
		bounds = bounds.expand(p)
	var src: Rect2 = e.src
	var tint: Color = e.get("tint", Color.WHITE)
	var verts: Array = []
	for p in pts:
		var uv := (src.position + (p - bounds.position) / bounds.size * src.size) / Vector2(img.width, img.height)
		var sp := p * MainMenuLayout.DESIGN_SCALE
		verts.append([sp.x, sp.y, uv.x, uv.y, tint])
	var tris: Array = []
	var idx := Geometry2D.triangulate_polygon(pts)
	for i in range(0, idx.size(), 3):
		tris.append([verts[idx[i]], verts[idx[i + 1]], verts[idx[i + 2]]])
	e["tris"] = tris
	if e.has("outline"):
		var r: Vector2i = e.outline
		var line := PackedVector2Array()
		for i in range(r.x, r.y + 1):
			line.append(pts[i] * MainMenuLayout.DESIGN_SCALE)
		e["outline_pts"] = line

# ---------------------------------------------------------------- lifecycle
func dispose() -> void:
	if hand_reanim and not hand_reanim.dead:
		hand_reanim.die()
	if trophy_particle and not trophy_particle.dead:
		trophy_particle.particle_system_die()

func sync_buttons() -> void:
	var almanac_available := App.can_show_almanac() or unlock_selector_cheat
	var store_open := App.can_show_store() or unlock_selector_cheat
	var zen_open := App.can_show_zen_garden() or unlock_selector_cheat
	var tree_open: bool = App.player_info != null and App.player_info.purchases.size() > PvZ.STORE_ITEM_TREE_OF_WISDOM \
		and App.player_info.purchases[PvZ.STORE_ITEM_TREE_OF_WISDOM] > 0

	almanac_button.disabled = not almanac_available
	almanac_button.visible = almanac_available
	quick_play_button.disabled = not App.has_finished_adventure()
	quick_play_button.visible = App.has_finished_adventure()
	store_button.disabled = not store_open
	store_button.visible = store_open
	zen_garden_button.disabled = not zen_open
	zen_garden_button.visible = zen_open
	tree_button.disabled = not tree_open
	tree_button.visible = tree_open

	for l in [[minigame_button, minigames_locked], [puzzle_button, puzzle_locked], [survival_button, survival_locked],
			[social_button, social_locked()]]:
		var b: NewLawnButton = l[0]
		b.set_color(ButtonWidget.COLOR_BKG, Color8(128, 128, 128) if l[1] else Color.WHITE)

func add_trophy_sparkle() -> void:
	var p := TROPHY_POS * MainMenuLayout.DESIGN_SCALE
	trophy_particle = App.add_tod_particle(p.x, p.y, PvZ.RENDER_LAYER_TOP, PvZ.PARTICLE_TROPHY_SPARKLE)

func sync_profile(show_loading: bool) -> void:
	if show_loading:
		loading = true
		loading = false

	if trophy_particle and not trophy_particle.dead:
		trophy_particle.particle_system_die()
	trophy_particle = null

	level = 1
	if App.player_info:
		level = App.player_info.level
	show_start_button = true
	# Community edition: these pages are always open. The original modes are hidden on the challenge screen
	# (see ChallengeScreen.page_has_content) until the mod adds its own.
	minigames_locked = false
	puzzle_locked = false
	survival_locked = false
	if App.player_info and not App.is_ice_demo():
		if level >= 2 or App.has_finished_adventure():
			show_start_button = false

	has_trophy = App.has_finished_adventure() and not App.is_trial_stage_locked()
	if has_trophy and selector_state != SELECTOR_OPEN:
		add_trophy_sparkle()
	sync_buttons()
	AlmanacDialog.almanac_init_for_player()
	BoardCore.shown_more_sun_tutorial = false  # BoardInitForPlayer

# ---------------------------------------------------------------- drawing
func _intro_ease(e: Dictionary) -> float:
	if intro_counter >= INTRO_FRAMES:
		return 1.0
	var delay: float = e.pos.x / MainMenuLayout.DESIGN_SIZE.x * 18.0
	var t := clampf((intro_counter - delay) / (INTRO_FRAMES - 18.0), 0.0, 1.0)
	return 1.0 - pow(1.0 - t, 3.0)

## Multiplayer is LAN only, so it greys out on a device that cannot host or join one, as well
## as before Adventure is finished.
func social_locked() -> bool:
	return not App.has_finished_adventure() or not Platform.supports_multiplayer()

func _is_locked(b: NewLawnButton) -> bool:
	return (b == minigame_button and minigames_locked) or (b == puzzle_button and puzzle_locked) or (b == survival_button and survival_locked) \
		or (b == social_button and social_locked())

func draw(g: Graphics) -> void:
	if App.get_dialog(PvZ.DIALOG_STORE) or App.get_dialog(PvZ.DIALOG_ALMANAC):
		return
	g.set_linear_blend(true)
	for e in scene:
		if e.has("poly"):
			_draw_poly(g, e)
		else:
			_draw_entry(g, e)
	g.set_colorize_images(false)
	g.set_draw_mode(Graphics.DRAWMODE_NORMAL)

func _draw_poly(g: Graphics, e: Dictionary) -> void:
	g.set_draw_mode(Graphics.DRAWMODE_NORMAL)
	g.draw_triangles_tex(e.image, e.tris)
	if e.has("outline_pts"):
		g.set_color(Color.BLACK)
		g.draw_polyline(e.outline_pts, 6.0 * MainMenuLayout.DESIGN_SCALE)

func _draw_entry(g: Graphics, e: Dictionary) -> void:
	var img: PvzImage = e.image
	if img == null:
		return
	var b: NewLawnButton = e.get("button_widget")
	if b and not b.visible and e.button in HIDDEN_WHEN_LOCKED:
		return
	var offset := Vector2.ZERO
	var color: Color = e.get("tint", Color.WHITE)
	if e.get("ui", false) or e.get("fade", false):
		var t := _intro_ease(e)
		if e.get("fade", false):
			color.a *= t
		else:
			offset.y = (1.0 - t) * 900.0
	if e.has("cloud_x"):
		offset.x = e.cloud_x
	var pop := 1.0
	if e.get("pop", 0) > 0:
		pop = 1.0 + 0.3 * sin(float(e.pop) / FLOWER_POP_FRAMES * PI)

	var xf := _entry_xform(e, offset, pop)
	if b:
		color *= b.get_color(ButtonWidget.COLOR_BKG)   # grey when locked, flashes while starting adventure
		if b.visible and not b.disabled:
			if b.is_down and b.is_over:
				xf.origin += Vector2(1, 1)
			if (b.is_over or b.is_down) and not _is_locked(b) and e.over_image:
				img = e.over_image

	g.set_colorize_images(true)
	g.set_color(color)
	g.set_draw_mode(Graphics.DRAWMODE_ADDITIVE if e.get("additive", false) else Graphics.DRAWMODE_NORMAL)
	g.draw_image_matrix(img, xf, _entry_src(e))
	g.set_draw_mode(Graphics.DRAWMODE_NORMAL)

	if e.has("name_bar") and App.player_info and App.player_info.name.length() > 0:
		_draw_sprite_text(g, e, xf, NAME_BAR, App.player_info.name, Res.get_font("FONT_BRIANNETOD16"), Color8(245, 245, 235))
	if e.has("level_plaque") and not App.is_ice_demo() and App.player_info:
		_draw_sprite_text(g, e, xf, LEVEL_PLAQUE, "LVL " + _level_string(), Res.get_font("FONT_DWARVENTODCRAFT12"), Color8(235, 235, 225))
	if e.has("label"):
		_draw_sprite_text(g, e, xf, BAR_LABEL, TodStrings.translate(e.label), Res.get_font("FONT_DWARVENTODCRAFT18"), Color8(235, 230, 205))

## Draws [param text] centred on a text area of a sprite (see NAME_BAR), following the sprite's transform.
func _draw_sprite_text(g: Graphics, e: Dictionary, xf: Transform2D, area: Array, text: String, font: ImageFont, col: Color) -> void:
	var centre: Vector2 = area[0] - _entry_src(e).size * 0.5
	var width := font.string_width(text)
	var k: float = minf(area[2], area[3] / maxf(width, 1.0))
	var local := Transform2D(deg_to_rad(area[1]), Vector2(k, k), 0.0, centre)
	# glyphs are positioned from the baseline
	var align := Transform2D(0.0, Vector2(-width * 0.5, font.get_ascent() * 0.4))
	var m := xf * local * align
	m.origin += Vector2(g.trans_x, g.trans_y)
	font.draw_string_matrix(g, m, text, col)

func _level_string() -> String:
	var stage := clampi(Tod.idiv(level - 1, 10) + 1, 1, 6)
	var sub := level - (stage - 1) * 10
	if App.is_trial_stage_locked() and (level >= 25 or App.has_finished_adventure()):
		stage = 3
		sub = 4
	return "%d-%d" % [stage, sub]

func draw_overlay(g: Graphics, _priority: int = 0) -> void:
	g.set_linear_blend(true)
	if App.player_info == null:
		return

	if has_trophy and selector_state != SELECTOR_OPEN:
		var trophy := _img("IMAGE_SUNFLOWER_TROPHY")
		var cel := 1 if App.earned_gold_trophy() else 0
		var p := TROPHY_POS * MainMenuLayout.DESIGN_SCALE
		var s := TROPHY_SCALE * MainMenuLayout.DESIGN_SCALE
		g.tod_draw_image_cel_scaled_f(trophy, p.x - trophy.get_cel_width() * s * 0.5, p.y - trophy.get_cel_height() * s * 0.5, cel, 0, s, s)
		if trophy_particle and not trophy_particle.dead:
			trophy_particle.draw(g)

	if zen_garden_button.visible and App.zen_garden.plants_need_water():
		var bx := zen_garden_button.x + int(zen_garden_button.width * 0.62)
		var by := zen_garden_button.y - 22
		g.draw_image(_img("IMAGE_PLANTSPEECHBUBBLE"), bx, by)
		g.draw_image(_img("IMAGE_WATERDROP"), bx + 17, by + 9)

	if hand_reanim and not hand_reanim.dead:
		var hg := g.copy()
		hg.set_clip_rect(0, 0, PvZ.BOARD_WIDTH, PvZ.BOARD_HEIGHT - 40)
		hand_reanim.draw(hg)

	tool_tip.draw(g)

func _trophy_rect() -> Rect2i:
	var trophy := _img("IMAGE_SUNFLOWER_TROPHY")
	var s := TROPHY_SCALE * MainMenuLayout.DESIGN_SCALE
	var size := Vector2(trophy.get_cel_width(), trophy.get_cel_height()) * s
	return Rect2i(Rect2(TROPHY_POS * MainMenuLayout.DESIGN_SCALE - size * 0.5, size))

func update_tooltip() -> void:
	if not App.has_finished_adventure() or App.get_dialog(PvZ.DIALOG_MESSAGE):
		return
	if has_trophy:
		var mx := App.widget_manager.last_mouse_x
		var my := App.widget_manager.last_mouse_y
		var r := _trophy_rect()
		if r.has_point(Vector2i(mx, my)):
			if App.earned_gold_trophy():
				tool_tip.set_label(App.pluralize(App.player_info.finished_adventure, "[GOLD_SUNFLOWER_TOOLTIP]", "[GOLD_SUNFLOWER_TOOLTIP_PLURAL]"))
			else:
				tool_tip.set_label("[SILVER_SUNFLOWER_TOOLTIP]")
			tool_tip.x = r.position.x + r.size.x / 2 - tool_tip.width / 2
			tool_tip.y = r.position.y - 30
			tool_tip.visible = true
			return
	tool_tip.visible = false
	tool_tip.update()

# ---------------------------------------------------------------- update
func update() -> void:
	super.update()
	update_tooltip()
	if App.zen_garden:   # not built yet if the menu is opened before loading finishes
		App.zen_garden.update_plant_needs()

	if movement_timer > 0:
		var py := calc_y_pos(current_y, destination_y)
		var px := calc_x_pos(current_x, destination_x)
		y = py
		x = px
		if App.achievement_screen:
			App.achievement_screen.y = py + PvZ.BOARD_HEIGHT - 1
		if App.quick_play_screen:
			App.quick_play_screen.x = px + PvZ.BOARD_WIDTH - 1
		overlay_widget.x = px
		overlay_widget.y = py
		movement_timer -= 1
	elif movement_timer == 0:
		current_y = y
		current_x = x
		if enable_buttons_transition:
			for b in _all_buttons():
				b.set_disabled(false)
			sync_buttons()
			enable_buttons_transition = false

	if trophy_particle and not trophy_particle.dead:
		trophy_particle.update()

	if starting_game:
		starting_game_counter += 1
		if starting_game_counter > 450:
			App.kill_game_selector()
			if App.is_ice_demo():
				App.pre_new_game(PvZ.GAMEMODE_CHALLENGE_ICE, false)
				return
			# WIDETWEAK: fixed the intro not playing the first time you start Adventure mode
			if App.is_first_time_adventure_mode() and level == 1:
				App.pre_new_game(PvZ.GAMEMODE_INTRO, false)
				return
			if App.player_info.needs_magic_taco_reward and level == 35:
				var store := App.show_store_screen()
				store.setup_for_intro(601)
				await store.wait_for_result(true)
				App.pre_new_game(PvZ.GAMEMODE_ADVENTURE, false)
				return
			if should_do_zen_tuturial_before_adventure():
				App.pre_new_game(PvZ.GAMEMODE_CHALLENGE_ZEN_GARDEN, false)
				App.zen_garden.setup_for_zen_tutorial()
				return
			App.pre_new_game(PvZ.GAMEMODE_ADVENTURE, true)
			return
		adventure_button.set_color(ButtonWidget.COLOR_BKG, Color8(80, 80, 80) if starting_game_counter % 20 < 10 else Color.WHITE)
		if starting_game_counter == 125:
			App.play_sample("SOUND_EVILLAUGH")

	match selector_state:
		SELECTOR_OPEN:
			if widget_manager:
				widget_manager.rehup_mouse()
			intro_counter += 1
			if intro_counter >= INTRO_FRAMES:
				for b in _all_buttons():
					b.mouse_visible = true

				if App.player_info == null:
					App.do_create_user_dialog()
					selector_state = SELECTOR_NEW_USER
				else:
					selector_state = SELECTOR_IDLE

				if has_trophy:
					add_trophy_sparkle()

				if App.player_info and App.player_info.needs_message_on_game_selector:
					App.player_info.needs_message_on_game_selector = 0
					App.write_current_user_config()
					App.lawn_message_box(PvZ.DIALOG_MESSAGE, "[ADVENTURE_COMPLETE_HEADER]", "[ADVENTURE_COMPLETE_BODY]", "[DIALOG_BUTTON_OK]", "", Dialog.BUTTONS_FOOTER)
		SELECTOR_NEW_USER:
			if App.get_dialog(PvZ.DIALOG_CREATEUSER) == null:
				selector_state = SELECTOR_SHOW_SIGN
		SELECTOR_SHOW_SIGN:
			selector_state = SELECTOR_IDLE

	for e in scene:
		if e.has("cloud_x"):
			e.cloud_x += CLOUD_SPEED
			var half: float = e.image.width * e.get("scale", Vector2.ONE).x * 0.5
			if e.pos.x + e.cloud_x - half > MainMenuLayout.DESIGN_SIZE.x:
				e.cloud_x = 900.0 - half - e.pos.x   # re-enter from behind the tree
		if e.get("pop", 0) > 0:
			e.pop -= 1

	if hand_reanim and not hand_reanim.dead:
		hand_reanim.update()

	if selector_state != SELECTOR_SUB_MENU and movement_timer == 0:
		App.kill_achievement_screen()
		App.kill_quick_play_screen()

func _managed_widgets() -> Array:
	var list := [adventure_button, minigame_button, puzzle_button, options_button, quit_button, help_button, store_button,
		almanac_button, survival_button, zen_garden_button, change_user_button, credits_button, tree_button, social_button,
		editor_button, overlay_widget]
	if HAS_ACHIEVEMENTS:
		list.append(achievement_button)
	if HAS_QUICKPLAY:
		list.append(quick_play_button)
	return list

func added_to_manager(wm: WidgetManager) -> void:
	super.added_to_manager(wm)
	for w in _managed_widgets():
		wm.add_widget(w)

func removed_from_manager(wm: WidgetManager) -> void:
	super.removed_from_manager(wm)
	for w in _managed_widgets():
		wm.remove_widget(w)

func order_in_manager_changed() -> void:
	for w in [overlay_widget, almanac_button, store_button, help_button, quit_button, options_button, adventure_button,
			minigame_button, puzzle_button, zen_garden_button, survival_button, change_user_button, credits_button, tree_button,
			social_button, editor_button]:
		widget_manager.put_infront(w, self)
	if HAS_ACHIEVEMENTS:
		widget_manager.put_infront(achievement_button, self)
	if HAS_QUICKPLAY:
		widget_manager.put_infront(quick_play_button, self)

func key_down(key: int) -> void:
	if App.konami_check.check(key):
		App.play_foley(PvZ.FOLEY_DROP)
		return
	if App.mustache_check.check(key) or App.moustache_check.check(key):
		App.play_foley(PvZ.FOLEY_POLEVAULT)
		App.mustache_mode = not App.mustache_mode
		return
	if App.super_mower_check.check(key) or App.super_mower_check2.check(key):
		App.play_foley(PvZ.FOLEY_ZAMBONI)
		App.super_mower_mode = not App.super_mower_mode
		return
	if App.future_check.check(key):
		App.play_sample("SOUND_BOING")
		App.future_mode = not App.future_mode
		return
	if App.pinata_check.check(key):
		if App.can_do_pinata_mode():
			App.play_foley(PvZ.FOLEY_JUICY)
			App.pinata_mode = not App.pinata_mode
		else:
			App.play_sample("SOUND_BUZZER")
		return
	if App.dance_check.check(key):
		if App.can_do_dance_mode():
			App.play_foley(PvZ.FOLEY_DANCER)
			App.dance_mode = not App.dance_mode
		else:
			App.play_sample("SOUND_BUZZER")
		return
	if App.daisy_check.check(key):
		if App.can_do_daisy_mode():
			App.play_sample("SOUND_LOADINGBAR_FLOWER")
			App.daisy_mode = not App.daisy_mode
		else:
			App.play_sample("SOUND_BUZZER")
		return
	if App.sukhbir_check.check(key):
		App.play_sample("SOUND_SUKHBIR")
		App.sukhbir_mode = not App.sukhbir_mode
		return

func key_char(ch: String) -> void:
	if starting_game:
		return
	if App.debug_keys_enabled:
		if ch == "u" and App.player_info:
			var pi := App.player_info
			pi.finished_adventure = 2
			pi.add_coins(50000)
			pi.has_used_cheat_keys = 1
			pi.has_unlocked_minigames = 1
			pi.has_unlocked_puzzle_mode = 1
			pi.has_unlocked_survival_mode = 1
			for i in range(1, 100):
				if i != PvZ.GAMEMODE_TREE_OF_WISDOM and i != PvZ.GAMEMODE_SCARY_POTTER_ENDLESS and i != PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_ENDLESS \
						and i != PvZ.GAMEMODE_SURVIVAL_ENDLESS_STAGE_3 and i - 1 < pi.challenge_records.size():
					pi.challenge_records[i - 1] = 20
			sync_profile(true)
			SaveGame.erase_saved_game(PvZ.GAMEMODE_ADVENTURE, pi.id)
		if ch == "c" or ch == "C":
			minigames_locked = false
			puzzle_locked = false
			survival_locked = false
			sync_buttons()
		if ch == "a":
			debug_text = not debug_text
			return
		if ch == "p":
			add_preview_profiles()

## GameSelector::AddPreviewProfiles (debug key 'p'): ready-made profiles at the start of each area.
func add_preview_profiles() -> void:
	var pm: ProfileMgr = App.profile_mgr
	var pr := pm.add_profile("2 Night")
	if pr:
		pr.level = 11
		pr.save_details()
	pr = pm.add_profile("3 Pool")
	if pr:
		pr.level = 21
		pr.has_unlocked_minigames = 1
		pr.coins = 400
		pr.purchases[PvZ.STORE_ITEM_PACKET_UPGRADE] = 1
		pr.save_details()
	pr = pm.add_profile("4 Fog")
	if pr:
		pr.level = 31
		pr.has_unlocked_minigames = 1
		pr.has_unlocked_survival_mode = 1
		pr.purchases[PvZ.STORE_ITEM_PACKET_UPGRADE] = 2
		pr.purchases[PvZ.STORE_ITEM_POOL_CLEANER] = 1
		pr.coins = 400
		pr.save_details()
	pr = pm.add_profile("5 Roof")
	if pr:
		pr.level = 41
		pr.has_unlocked_minigames = 1
		pr.has_unlocked_puzzle_mode = 1
		pr.has_unlocked_survival_mode = 1
		pr.purchases[PvZ.STORE_ITEM_PACKET_UPGRADE] = 2
		pr.purchases[PvZ.STORE_ITEM_POOL_CLEANER] = 1
		pr.coins = 500
		pr.save_details()
	pr = pm.add_profile("Complete")
	if pr:
		pr.level = 1
		pr.finished_adventure = 1
		pr.has_unlocked_minigames = 1
		pr.has_unlocked_puzzle_mode = 1
		pr.has_unlocked_survival_mode = 1
		pr.purchases[PvZ.STORE_ITEM_PACKET_UPGRADE] = 2
		pr.purchases[PvZ.STORE_ITEM_POOL_CLEANER] = 1
		pr.purchases[PvZ.STORE_ITEM_ROOF_CLEANER] = 1
		pr.coins = 1000
		pr.save_details()
	pr = pm.add_profile("Full Unlock")
	if pr:
		pr.level = 1
		pr.finished_adventure = 2
		pr.add_coins(50000)
		for item in [PvZ.STORE_ITEM_FERTILIZER, PvZ.STORE_ITEM_BUG_SPRAY, PvZ.STORE_ITEM_CHOCOLATE, PvZ.STORE_ITEM_TREE_FOOD]:
			pr.purchases[item] = PlayerInfo.PURCHASE_COUNT_OFFSET + 5
		pr.has_unlocked_minigames = 1
		pr.has_unlocked_puzzle_mode = 1
		for item in [PvZ.STORE_ITEM_PLANT_GATLINGPEA, PvZ.STORE_ITEM_PLANT_TWINSUNFLOWER, PvZ.STORE_ITEM_PLANT_GLOOMSHROOM,
				PvZ.STORE_ITEM_PLANT_CATTAIL, PvZ.STORE_ITEM_PLANT_WINTERMELON, PvZ.STORE_ITEM_PLANT_GOLD_MAGNET,
				PvZ.STORE_ITEM_PLANT_SPIKEROCK, PvZ.STORE_ITEM_PLANT_COBCANNON, PvZ.STORE_ITEM_PLANT_IMITATER,
				PvZ.STORE_ITEM_POOL_CLEANER, PvZ.STORE_ITEM_ROOF_CLEANER, PvZ.STORE_ITEM_PHONOGRAPH, PvZ.STORE_ITEM_GARDENING_GLOVE,
				PvZ.STORE_ITEM_MUSHROOM_GARDEN, PvZ.STORE_ITEM_WHEEL_BARROW, PvZ.STORE_ITEM_AQUARIUM_GARDEN, PvZ.STORE_ITEM_TREE_OF_WISDOM]:
			pr.purchases[item] = 1
		pr.purchases[PvZ.STORE_ITEM_PACKET_UPGRADE] = 3
		pr.challenge_records[PvZ.GAMEMODE_TREE_OF_WISDOM - 1] = 1
		# The original writes these trophies to the *current* profile, not the new one; kept as-is.
		if App.player_info:
			for i in range(1, 100):
				if i != PvZ.GAMEMODE_TREE_OF_WISDOM and i != PvZ.GAMEMODE_SCARY_POTTER_ENDLESS and i != PvZ.GAMEMODE_PUZZLE_I_ZOMBIE_ENDLESS \
						and i != PvZ.GAMEMODE_SURVIVAL_ENDLESS_STAGE_3 and i - 1 < App.player_info.challenge_records.size():
					App.player_info.challenge_records[i - 1] = 20
		pr.save_details()
	pm.save()

func mouse_down(mx: int, my: int, _click_count: int) -> void:
	# Flowers pop when clicked (replaces the selector reanim's falling flowers).
	for e in scene:
		if not e.has("pop") or e.pop > 0 or e.image == null:
			continue
		var r: float = maxf(e.image.width, e.image.height) * e.get("scale", Vector2.ONE).x * MainMenuLayout.DESIGN_SCALE * 0.4
		if Vector2(mx, my).distance_to(e.pos * MainMenuLayout.DESIGN_SCALE) < r:
			e.pop = FLOWER_POP_FRAMES
			App.play_foley(PvZ.FOLEY_LIMBS_POP)
			break
	if App.tod_cheat_keys and starting_game and starting_game_counter < 450:
		starting_game_counter = 450

func button_mouse_enter(bid: int) -> void:
	if (bid == GAMESELECTOR_MINIGAME and minigames_locked) or (bid == GAMESELECTOR_PUZZLE and puzzle_locked) or (bid == GAMESELECTOR_SURVIVAL and survival_locked):
		return
	if bid == GAMESELECTOR_SOCIAL and social_locked():
		return
	App.play_foley(PvZ.FOLEY_BLEEP)

func button_press(bid: int, _count: int = 1) -> void:
	if bid in [GAMESELECTOR_ADVENTURE, GAMESELECTOR_MINIGAME, GAMESELECTOR_PUZZLE, GAMESELECTOR_SURVIVAL]:
		App.play_sample("SOUND_GRAVEBUTTON")
	else:
		App.play_sample("SOUND_TAP")

func _set_buttons_disabled(d: bool) -> void:
	for b in _all_buttons():
		b.set_disabled(d)

func clicked_adventure() -> void:
	if App.is_trial_stage_locked() and (level >= 25 or App.has_finished_adventure()):
		var r := await App.lawn_message_box(PvZ.DIALOG_MESSAGE, "[REPLAY_LEVEL_HEADER]", "[REPLAY_LEVEL_BODY]", "[DIALOG_BUTTON_YES]", "[DIALOG_BUTTON_NO]", Dialog.BUTTONS_YES_NO)
		if r == Dialog.ID_NO:
			return
		App.player_info.level = 24
		App.player_info.finished_adventure = 0
		SaveGame.erase_saved_game(PvZ.GAMEMODE_ADVENTURE, App.player_info.id)

	App.music.stop_all_music()
	App.play_sample("SOUND_LOSEMUSIC")
	starting_game = true
	_set_buttons_disabled(true)

	hand_reanim = App.add_reanimation(-70.0 + PvZ.BOARD_ADDITIONAL_WIDTH, 10.0 + PvZ.BOARD_OFFSET_Y, 0, PvZ.REANIM_ZOMBIE_HAND)
	hand_reanim.loop_type = Reanimation.REANIM_PLAY_ONCE_AND_HOLD
	App.play_foley(PvZ.FOLEY_DIRT_RISE)
	for i in hand_reanim.definition.tracks.size():
		if hand_reanim.definition.tracks[i].name.substr(0, 4).to_lower() == "rock":
			hand_reanim.track_instances[i].ignore_clip_rect = true

func should_do_zen_tuturial_before_adventure() -> bool:
	return not App.has_finished_adventure() and App.player_info.level == 45 and App.player_info.num_potted_plants() == 0

func button_depress(bid: int) -> void:
	if bid == GAMESELECTOR_MINIGAME and minigames_locked:
		App.lawn_message_box(PvZ.DIALOG_MESSAGE, "[MODE_LOCKED]", "[MINIGAME_LOCKED_MESSAGE]", "[DIALOG_BUTTON_OK]", "", Dialog.BUTTONS_FOOTER)
		return
	if bid == GAMESELECTOR_PUZZLE and puzzle_locked:
		App.lawn_message_box(PvZ.DIALOG_MESSAGE, "[MODE_LOCKED]", "[PUZZLE_LOCKED_MESSAGE]", "[DIALOG_BUTTON_OK]", "", Dialog.BUTTONS_FOOTER)
		return
	if bid == GAMESELECTOR_SURVIVAL and survival_locked:
		App.lawn_message_box(PvZ.DIALOG_MESSAGE, "[MODE_LOCKED]", "[SURVIVAL_LOCKED_MESSAGE]", "[DIALOG_BUTTON_OK]", "", Dialog.BUTTONS_FOOTER)
		return
	if bid == GAMESELECTOR_SOCIAL and not Platform.supports_multiplayer():
		App.lawn_message_box(PvZ.DIALOG_MESSAGE, "[MODE_LOCKED]", Platform.multiplayer_unavailable_reason(), "[DIALOG_BUTTON_OK]", "", Dialog.BUTTONS_FOOTER)
		return
	if bid == GAMESELECTOR_SOCIAL and not App.has_finished_adventure():
		App.lawn_message_box(PvZ.DIALOG_MESSAGE, "[MODE_LOCKED]", "Finish Adventure mode to unlock multiplayer Co-op and Versus.", "[DIALOG_BUTTON_OK]", "", Dialog.BUTTONS_FOOTER)
		return

	match bid:
		GAMESELECTOR_ADVENTURE:
			clicked_adventure()
		GAMESELECTOR_MINIGAME:
			App.kill_game_selector()
			App.show_challenge_screen(PvZ.CHALLENGE_PAGE_CHALLENGE)
		GAMESELECTOR_PUZZLE:
			App.kill_game_selector()
			App.show_challenge_screen(PvZ.CHALLENGE_PAGE_PUZZLE)
		GAMESELECTOR_SURVIVAL:
			App.kill_game_selector()
			App.show_challenge_screen(PvZ.CHALLENGE_PAGE_SURVIVAL)
		GAMESELECTOR_QUIT:
			App.confirm_quit()
		GAMESELECTOR_HELP:
			App.kill_game_selector()
			App.show_award_screen(PvZ.AWARD_HELP_ZOMBIENOTE, false)
		GAMESELECTOR_OPTIONS:
			App.do_new_options(true)
		GAMESELECTOR_CHANGE_USER:
			App.do_user_dialog()
		GAMESELECTOR_STORE:
			var store := App.show_store_screen()
			await store.wait_for_result(true)
			if store.go_to_tree_now:
				App.kill_game_selector()
				App.pre_new_game(PvZ.GAMEMODE_TREE_OF_WISDOM, false)
			else:
				App.music.make_sure_music_is_playing(PvZ.MUSIC_TUNE_TITLE_CRAZY_DAVE_MAIN_THEME)
		GAMESELECTOR_ALMANAC:
			var almanac := App.do_almanac_dialog()
			await almanac.wait_for_result(true)
			App.music.make_sure_music_is_playing(PvZ.MUSIC_TUNE_TITLE_CRAZY_DAVE_MAIN_THEME)
		GAMESELECTOR_ACHIEVEMENT:
			movement_timer = 75
			destination_y = -PvZ.BOARD_HEIGHT
			selector_state = SELECTOR_SUB_MENU
			App.show_achievement_screen()
			_set_buttons_disabled(true)
		GAMESELECTOR_QUICK_PLAY:
			movement_timer = 75
			destination_x = -PvZ.BOARD_WIDTH
			selector_state = SELECTOR_SUB_MENU
			App.show_quick_play_screen()
			_set_buttons_disabled(true)
		GAMESELECTOR_ZEN_GARDEN:
			App.kill_game_selector()
			App.pre_new_game(PvZ.GAMEMODE_CHALLENGE_ZEN_GARDEN, false)
			if should_do_zen_tuturial_before_adventure():
				App.zen_garden.setup_for_zen_tutorial()
		GAMESELECTOR_CREDITS:
			App.kill_game_selector()
			App.show_mini_credit_screen()
		GAMESELECTOR_TREE_OF_WISDOM:
			App.kill_game_selector()
			App.pre_new_game(PvZ.GAMEMODE_TREE_OF_WISDOM, false)
		GAMESELECTOR_EDITOR:
			App.show_level_editor()
		GAMESELECTOR_SOCIAL:
			var d := NetConnectDialog.new()
			App.center_dialog(d, d.width, d.height)
			App.add_dialog(NetSession.DIALOG_CONNECT, d)
			App.widget_manager.set_focus(d.ip_edit)

func calc_y_pos(_og_y: int, new_y: int) -> int:
	destination_y = new_y
	return Tod.animate_curve(75, 0, movement_timer, current_y, destination_y, Tod.CURVE_EASE_IN_OUT)

func calc_x_pos(_og_x: int, new_x: int) -> int:
	destination_x = new_x
	return Tod.animate_curve(75, 0, movement_timer, current_x, destination_x, Tod.CURVE_EASE_IN_OUT)
